import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Projet",
  description: "Generated by create next app",
  icons: {
    icon: "/calme.ico", // ✅ Chemin relatif à la racine du site, PAS "public/"
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <html lang="en">
      <body className="bg-[#0A141E] text-gray-300 min-h-screen">
        <div className="flex justify-center">
         
            {children}
          
        </div>
      </body>
    </html>
  );
}
