import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "./components/Sidebar";
import { ThemeProvider } from "next-themes";
import { motion } from 'framer-motion';

import { itemVariants,  containerVariants} from "@/lib/Fonction";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Projet",
  description: "Generated by create next app",
  icons: {
    icon: "/trady.ico", // ✅ Chemin relatif à la racine du site, PAS "public/"
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
  <html lang="en" suppressHydrationWarning>
    <body className="bg-[#0A141E] text-gray-300 min-h-screen">        
      <div className="flex justify-center">
        <div className="flex w-full bg-[#F3F4F6] dark:bg-gradient-to-br dark:from-gray-900 dark:to-black">
          <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
            {children}
          </ThemeProvider>
        </div> 
      </div>
    </body>
  </html>
      
  );
}
